### ISSUE TITLE
Null Reference on persisting

### ISSUE THREAD

**Issue by simbadltd** [markmeeus/MarcelloDB#31]
at MarcelloDB.Collections.IndexedValue`2.<get_ValueFunction>b__2(TObj o)
at MarcelloDB.Collections.IndexedValue`2.GetValue(Object o)
at MarcelloDB.Collections.IndexedIDValue`1.GetKey(Object o, Int64 address)
at MarcelloDB.Collections.Collection`1.RegisterInIndexes(T o, Record record, Int64 originalAddress, T originalObject)
at MarcelloDB.Collections.Collection`1.PersistInternal(T obj)
at MarcelloDB.Collections.Collection`1.<>c__DisplayClass4.<Persist>b__3()
at MarcelloDB.Collections.Collection`1.<>c__DisplayClassa.<Transacted>b__9()
at MarcelloDB.Session.Transaction(Action action)
at MarcelloDB.Collections.Collection`1.Transacted(Action action)
at MarcelloDB.Collections.Collection`1.Persist(T obj)

instance of class:
public sealed class Product
    {
        public Guid Id { get; set; }

```
    public string Article { get; set; }

    public string Name { get; set; }

    public string MetaKeywords { get; set; }

    public string MetaDescription { get; set; }

    public string Description { get; set; }

    public string Comment { get; set; }

    public DateTime DateAdded { get; set; }

    public DateTime DateExported { get; set; }

    public DateTime DateUpdated { get; set; }

    public bool HasErrors { get; set; }

    public Guid ProductStoreCategoryId { get; set; }

    public Guid ManufacturerId { get; set; }

    public List<ProductParameterValue> ParameterValues { get; set; }

    public List<ProductImage> ProductImages { get; set; }
}
```

**Comment by markmeeus** [comment]
HI Simbadltd,

First of all, thank you for reporting the issue.

That stacktrace tells met that somehow the indexing mechanism is trying to access a non-existing property on Product.

It could be the Id mechanism, or something in your index definition.

Are you using an IndexDefinition? If so, could you paste that code here as well? 

Also, are you on version 0.3 ?

**Comment by markmeeus** [comment]
Hi Simbadltd,

I found the issue, it's a bug.
You may be able to work around the issue by wrapping the Id property with an ID property, or you can wait a few days for version 0.3.2.

The workaround should look like this:

``` cs
public Guid ID { get { return this.Id; } }
```

**Comment by simbadltd** [comment]
Hi Mark!

I'm not using IndexDefinition.

I've written test code and it looks very simple:

```
            using (var db = Database.Open())
            {
                var file = db.Session[FileName];
                var products = file.Collection<Product>(CollectionName);
                products.Persist(entity);
                return entity.Id;
            }
```

Thank you for very fast reply. I'll try workaround and continue to test your engine.

**Comment by markmeeus** [comment]
Just wanted to let you know that marcellodb doesn't assign ids.
If your entity doens't have a value for Id yet, you will want to assign a new guid before persisting.

**Comment by simbadltd** [comment]
Thx!!! I've added Guid generation into my code. But it would be cool if Marcellodb would be able to assign ids automatically (int auto-increment fields for example or guids) :)

**Comment by simbadltd** [comment]
Great. Workaround is working. But it is interesting that I have to remove all data files because I was catching OutOfMemory exception on Persist call:

   at MarcelloDB.netfx.Storage.FileStorageStream.Read(Int64 address, Int32 length)
   at MarcelloDB.Storage.StreamActors.Reader.Read(Int64 address, Int32 length)
   at MarcelloDB.Storage.StreamActors.JournalledReader.Read(Int64 address, Int32 length)
   at MarcelloDB.Storage.StorageEngine.Read(Int64 address, Int32 length)
   at MarcelloDB.Records.RecordManager.ReadEntireRecord(Int64 address)
   at MarcelloDB.Records.RecordManager.GetRecord(Int64 address)
   at MarcelloDB.Records.RecordManager.GetNamedRecordIndexRecord()
   at MarcelloDB.Records.RecordManager.RegisterNamedRecordAddress(String name, Int64 recordAddress)
   at MarcelloDB.Index.BTree.RecordBTreeDataProvider`1.SaveMetaRecord()
   at MarcelloDB.Index.BTree.RecordBTreeDataProvider`1.Flush()
   at MarcelloDB.Index.RecordIndex`1.FlushProvider()
   at MarcelloDB.Index.RecordIndex`1.Register(TNodeKey keyValue, Int64 recordAddress)
   at MarcelloDB.Records.RecordManager.<>c__DisplayClass6.<RegisterRecycledRecordsInEmptyRecordIndex>b__5()
   at MarcelloDB.Records.RecordManager.<>c__DisplayClass9.<UsingEmptyRecordIndex>b__8()
   at MarcelloDB.Records.RecordManager.UsingEmptyRecordIndex[T](Func`1 func)
   at MarcelloDB.Records.RecordManager.UsingEmptyRecordIndex(Action action)
   at MarcelloDB.Records.RecordManager.RegisterRecycledRecordsInEmptyRecordIndex()
   at MarcelloDB.Records.RecordManager.SaveState()
   at MarcelloDB.Transactions.Transaction.Commit()
   at MarcelloDB.Transactions.Transaction.Leave()
   at MarcelloDB.Session.Transaction(Action action)
   at MarcelloDB.Collections.Collection`1.Transacted(Action action)
   at MarcelloDB.Collections.Collection`1.Persist(T obj)
   at Products.Infrastructure.FakeProductRepository.Save(Product entity) in 

data and journal files zipped:
[data.zip](https://github.com/markmeeus/MarcelloDB/files/211277/data.zip)

**Comment by simbadltd** [comment]
It seems workaround for OutOfMemory is to use IndexDefinition:

```
            using (var db = Database.Open())
            {
                var file = db.Session[FileName];
                var products = file.Collection<Product, ProductIndexDefinition>(CollectionName);
                products.Persist(entity);
                return entity.ID;
            }
```

**Comment by markmeeus** [comment]
That's pretty bizar :-)
What are the exact steps to reproduce the OutOfMemory?

**Comment by simbadltd** [comment]
I've opened issue #32. Will answer there.

**Comment by markmeeus** [comment]
I have published version 0.3.2 on nuget.org.
Would you be so kind to verify that the workaround is no longer necessary?

**Comment by simbadltd** [comment]
Verified. Persisting works with Guid Id property. Workaround is no longer needed.

**Comment by markmeeus** [comment]
Thanks!
Closing the issue.
