### ISSUE TITLE
OutOfMemory exception when persisting second and subsequent objects

### ISSUE THREAD

**Issue by simbadltd** [markmeeus/MarcelloDB#32]
It is interesting that I have to remove all data files because I was catching OutOfMemory exception on Persist call:

at MarcelloDB.netfx.Storage.FileStorageStream.Read(Int64 address, Int32 length)
at MarcelloDB.Storage.StreamActors.Reader.Read(Int64 address, Int32 length)
at MarcelloDB.Storage.StreamActors.JournalledReader.Read(Int64 address, Int32 length)
at MarcelloDB.Storage.StorageEngine.Read(Int64 address, Int32 length)
at MarcelloDB.Records.RecordManager.ReadEntireRecord(Int64 address)
at MarcelloDB.Records.RecordManager.GetRecord(Int64 address)
at MarcelloDB.Records.RecordManager.GetNamedRecordIndexRecord()
at MarcelloDB.Records.RecordManager.RegisterNamedRecordAddress(String name, Int64 recordAddress)
at MarcelloDB.Index.BTree.RecordBTreeDataProvider1.SaveMetaRecord() at MarcelloDB.Index.BTree.RecordBTreeDataProvider1.Flush()
at MarcelloDB.Index.RecordIndex1.FlushProvider() at MarcelloDB.Index.RecordIndex1.Register(TNodeKey keyValue, Int64 recordAddress)
at MarcelloDB.Records.RecordManager.<>c__DisplayClass6.b__5()
at MarcelloDB.Records.RecordManager.<>c__DisplayClass9.b__8()
at MarcelloDB.Records.RecordManager.UsingEmptyRecordIndexT
at MarcelloDB.Records.RecordManager.UsingEmptyRecordIndex(Action action)
at MarcelloDB.Records.RecordManager.RegisterRecycledRecordsInEmptyRecordIndex()
at MarcelloDB.Records.RecordManager.SaveState()
at MarcelloDB.Transactions.Transaction.Commit()
at MarcelloDB.Transactions.Transaction.Leave()
at MarcelloDB.Session.Transaction(Action action)
at MarcelloDB.Collections.Collection1.Transacted(Action action) at MarcelloDB.Collections.Collection1.Persist(T obj)
at Products.Infrastructure.FakeProductRepository.Save(Product entity) in

It seems workaround for OutOfMemory is to use IndexDefinition:

```
            using (var db = Database.Open())
            {
                var file = db.Session[FileName];
                var products = file.Collection<Product, ProductIndexDefinition>(CollectionName);
                products.Persist(entity);
                return entity.ID;
            }

```

**Comment by simbadltd** [comment]
Steps:
1) Create instance of the following class:

```
    public sealed class Product: Entity
    {
        public string Article { get; set; }

        public string Name { get; set; }

        public string MetaKeywords { get; set; }

        public string MetaDescription { get; set; }

        public string Description { get; set; }

        public string Comment { get; set; }

        public DateTime DateAdded { get; set; }

        public DateTime DateExported { get; set; }

        public DateTime DateUpdated { get; set; }

        public bool HasErrors { get; set; }

        public Guid ProductStoreCategoryId { get; set; }

        public Guid ManufacturerId { get; set; }

        public List<ProductParameterValue> ParameterValues { get; set; }

        public List<ProductImage> ProductImages { get; set; }
    }
```

2) Persist into db using following code:

```
        private const string FileName = "products.data";

        private const string CollectionName = "products";
...
            using (var db = Database.Open())
            {
                var file = db.Session[FileName];
                var products = file.Collection<Product>(CollectionName);
                products.Persist(entity);
                return entity.ID;
            }
```

Database.Open do the following:

```
            var platform = new Platform();

            var path = PathUtils.ToAbsolutePath(DataPath);
            Directory.CreateDirectory(path);
            _session = new Session(platform, path);
```

3) Then I'm creating second object and trying to persist it using the same code as in item 2. And i'm getting OutOfMemory exception.

It is interesting that first object has no problems with persisting but the second has. Pls note that I'm instantiating Session object for every persist call.

**Comment by markmeeus** [comment]
Indeed, actually pretty easy to simulate.
I'll look into it.

**Comment by markmeeus** [comment]
Thank you soo much for reporting this issue!

It will be fixed as well in 0.3.2.

Also, it's perfectly fine to keep your session in a singleton or a static for the duration of your process.
This way you'll avoid creating 2 sessions in the same folder, (maybe in a second thread), the second session will crash.

In later versions (when I'll be working on performance) caching will be added to the session, so there will be a good reason to keep the session open.

**Comment by simbadltd** [comment]
Great news. Thank you!

I will continue testing.

**Comment by simbadltd** [comment]
So singleton session means that data files will be blocked until Application closed?

**Comment by markmeeus** [comment]
Yes, exactly. 
Well, not just all files in the folder, only the ones for which you obtained a collection file.

**Comment by simbadltd** [comment]
Ok. Thx. Will try singleton approach.

**Comment by markmeeus** [comment]
I have published version 0.3.2 on nuget.org.
Would you be so kind to verify that the workaround is no longer necessary?

**Comment by simbadltd** [comment]
Verified. Persisting of second and subsequent objects works without IndexDefinition. Workaround is no longer needed.

**Comment by markmeeus** [comment]
Thx!
Closing the issue.
