### ISSUE TITLE
Issue when trying to access database on Release mode (Xamarin.Forms + Android)

### ISSUE THREAD

**Issue by agharium** [markmeeus/MarcelloDB#70]
Hi!

I'm using MarcelloDB on Xamarin.Forms (Android & iOS). It's working great on Android Debug mode, but when I set to Release, an error occurs when I first try to access the database. I got the stacktrace from the device's logcat.

First, it throws this:

```java
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'MarcelloDB.Collections.IndexedIDValue<ProMama.Models.Sincronizacao,int>' does not contain a definition for 'SetContext'
  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,object,MarcelloDB.Collections.Collection,MarcelloDB.Session,MarcelloDB.Records.RecordManager,MarcelloDB.Serialization.IObjectSerializer`1<ProMama.Models.Sincronizacao>,string)
  at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid6[T0,T1,T2,T3,T4,T5] (System.Runtime.CompilerServices.CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5) [0x0013a] in <838860cadd96464196ed5d485479b05a>:0 
  at MarcelloDB.Index.IndexDefinition`1[T].SetContext (MarcelloDB.Collections.Collection collection, MarcelloDB.Session session, MarcelloDB.Records.RecordManager recordManager, MarcelloDB.Serialization.IObjectSerializer`1[T] serializer) [0x000a6] in <600bc19d08ba440983cfa234add9d426>:0 
  at MarcelloDB.Collections.Collection`2[T,TID]..ctor (MarcelloDB.Session session, MarcelloDB.Collections.CollectionFile collectionFile, System.String name, MarcelloDB.Serialization.IObjectSerializer`1[T] serializer, MarcelloDB.Records.RecordManager recordManager, System.Func`2[T,TResult] idFunc) [0x00061] in <600bc19d08ba440983cfa234add9d426>:0 
  at MarcelloDB.Collections.CollectionFile+<>c__DisplayClass13_0`2[T,TID].<Collection>b__0 () [0x00059] in <600bc19d08ba440983cfa234add9d426>:0 
  at MarcelloDB.Session.Transaction (System.Action action) [0x00053] in <600bc19d08ba440983cfa234add9d426>:0 
  at MarcelloDB.Collections.CollectionFile.Collection[T,TID] (System.String collectionName, System.Func`2[T,TResult] idFunc) [0x00064] in <600bc19d08ba440983cfa234add9d426>:0 
  at ProMama.Database.Controllers.SincronizacaoDatabaseController..ctor () [0x0002e] in <e479508103a1421790072cc07c0b8957>:0 
  at ProMama.App.get_SincronizacaoDatabase () [0x00007] in <e479508103a1421790072cc07c0b8957>:0 
  at ProMama.App..ctor () [0x00036] in <e479508103a1421790072cc07c0b8957>:0 
  at ProMama.Droid.MainActivity.OnCreate (Android.OS.Bundle bundle) [0x00062] in <a32b5e39d76e47e9aa52544d95c42d2f>:0 
  at Android.Support.V4.App.FragmentActivity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <1d94d07e534740c08702e276f814d97b>:0 
  at (wrapper dynamic-method) System.Object.eda4c82a-cb60-4cd9-9c0e-b1652e2d2fd9(intptr,intptr,intptr)
```

A little later (milliseconds), it throws this:

```java
android.runtime.JavaProxyThrowable: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'MarcelloDB.Collections.IndexedIDValue<ProMama.Models.Sincronizacao,int>' does not contain a definition for 'SetContext'
  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,object,MarcelloDB.Collections.Collection,MarcelloDB.Session,MarcelloDB.Records.RecordManager,MarcelloDB.Serialization.IObjectSerializer`1<ProMama.Models.Sincronizacao>,string)
  at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid6[T0,T1,T2,T3,T4,T5] (System.Runtime.CompilerServices.CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5) [0x0013a] in <838860cadd96464196ed5d485479b05a>:0 
  at MarcelloDB.Index.IndexDefinition`1[T].SetContext (MarcelloDB.Collections.Collection collection, MarcelloDB.Session session, MarcelloDB.Records.RecordManager recordManager, MarcelloDB.Serialization.IObjectSerializer`1[T] serializer) [0x000a6] in <600bc19d08ba440983cfa234add9d426>:0 
  at MarcelloDB.Collections.Collection`2[T,TID]..ctor (MarcelloDB.Session session, MarcelloDB.Collections.CollectionFile collectionFile, System.String name, MarcelloDB.Serialization.IObjectSerializer`1[T] serializer, MarcelloDB.Records.RecordManager recordManager, System.Func`2[T,TResult] idFunc) [0x00061] in <600bc19d08ba440983cfa234add9d426>:0 
  at MarcelloDB.Collections.CollectionFile+<>c__DisplayClass13_0`2[T,TID].<Collection>b__0 () [0x00059] in <600bc19d08ba440983cfa234add9d426>:0 
  at MarcelloDB.Session.Transaction (System.Action action) [0x00053] in <600bc19d08ba440983cfa234add9d426>:0 
  at MarcelloDB.Collections.CollectionFile.Collection[T,TID] (System.String collectionName, System.Func`2[T,TResult] idFunc) [0x00064] in <600bc19d08ba440983cfa234add9d426>:0 
  at ProMama.Database.Controllers.SincronizacaoDatabaseController..ctor () [0x0002e] in <e479508103a1421790072cc07c0b8957>:0 
  at ProMama.App.get_SincronizacaoDatabase () [0x00007] in <e479508103a1421790072cc07c0b8957>:0 
  at ProMama.App..ctor () [0x00036] in <e479508103a1421790072cc07c0b8957>:0 
  at ProMama.Droid.MainActivity.OnCreate (Android.OS.Bundle bundle) [0x00062] in <a32b5e39d76e47e9aa52544d95c42d2f>:0 
  at Android.Support.V4.App.FragmentActivity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <1d94d07e534740c08702e276f814d97b>:0 
  at (wrapper dynamic-method) System.Object.eda4c82a-cb60-4cd9-9c0e-b1652e2d2fd9(intptr,intptr,intptr)
  at md53e3df0725c458c2699e003c3433b7eb1.MainActivity.n_onCreate(Native Method)
  at md53e3df0725c458c2699e003c3433b7eb1.MainActivity.onCreate(MainActivity.java:30)
  at android.app.Activity.performCreate(Activity.java:7174)
  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)
  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
  at android.app.ActivityThread.-wrap11(Unknown Source:0)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
  at android.os.Handler.dispatchMessage(Handler.java:105)
  at android.os.Looper.loop(Looper.java:164)
  at android.app.ActivityThread.main(ActivityThread.java:6944)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

I thought it could be something related to storage permissions, but even if I manually activate the permission on the device's settings, it won't run.

This is the line of code that crashes. It's on my App.cs (application launch):

```csharp
app._sync = SincronizacaoDatabase.Find();
```

And this is my controller's implementation ('SincronizacaoDatabase' is an instance of it):

```csharp
using MarcelloDB;
using MarcelloDB.Collections;
using Newtonsoft.Json;
using ProMama.Models;

namespace ProMama.Database.Controllers
{
    public class SincronizacaoDatabaseController
    {
        Session session = App.DB;

        private CollectionFile SincronizacaoFile { get; set; }
        private Collection<Sincronizacao, int> SincronizacaoCollection { get; set; }

        public SincronizacaoDatabaseController()
        {
            SincronizacaoFile = session["sincronizacoes.dat"];
            SincronizacaoCollection = SincronizacaoFile.Collection<Sincronizacao, int>("sincronizacoes", obj => obj.id);
        }

        public void Save(Sincronizacao obj)
        {
            SincronizacaoCollection.Persist(obj);
        }

        public Sincronizacao Find()
        {
            return SincronizacaoCollection.Find(1);
        }

        public void DeleteSincronizacao()
        {
            SincronizacaoCollection.Destroy(1);
        }

        public void DumpTable()
        {
            System.Diagnostics.Debug.WriteLine(JsonConvert.SerializeObject(SincronizacaoCollection.All, Formatting.Indented));
        }
    }
}
```

Of course, on the very first attempt to 'find' an occurrence, it should return null (I check for it later on my code logic and it has been working this far on Debug haha). I also tried to access another table before the 'Sincronizacao' one, but it didn't work either (throws out the same error, just changing the class name).

This issue is puzzling me, because it was working just so fine on Debug.. but this is my first real kind-of-big project, so I really don't know what I got to do (the specifics) when changing from Debug to Release mode. Maybe it's something really obvious that I'm missing hehe.

I have been using MarcelloDB for quite some time and it has been great so far. You really should be proud of your work :)

I also hope you can help me, hehe.

Thanks :)

**Comment by markmeeus** [comment]
Hi José Paulo,

Thanks for reporting this.

I was unaware of this issue, but is indeed a problem within MarcelloDB. 
A small part depends on DLR and that's why it fails there.

I will publish a fix soon, for now, could you try to change the linker settings in your ios project so that is only links Framework Assemblies? Maybe that helps you out for now.

**Comment by agharium** [comment]
Hi Mark,

Thanks for answering.

Changing link settings didn't help. I'll be waiting for the fix. 

The fix is something hard to code? I actually need to publish the app in two weeks or so (it doesn't depends on me, it's third party stuff, otherwise I would wait more).

If you could tell me the fix' ETA, I would be very glad. Also, I'm up to try out any pre-release version,

Thanks, Mark.

**Comment by markmeeus** [comment]
Hi,

I'm a bit short on time these days so if you would be willing to test, that would be great.
I will put a pre-release on nuget in the comming days in which the offending code will be replaced.

Could you test in the meantime if the issue goes away with linker behaviour set to 'Dont link'

I'm creating the fix based on the assumption that it's the linker which removes 'dead' code which actually isn't dead...., so if changing the linker settings don't change the behaviour, I may be looking in the wrong direction.

**Comment by agharium** [comment]
Hi Mark,

I have just tested it out here. It didn't work with link settings at "none". Same errors and output as before.

If there's anything I could do to help you solve this, I'm up to it.

Thanks for helping me out!

**Comment by markmeeus** [comment]
Hi José Paulo,

I have published 1.0.8-beta on nuget.
It could take a few hours to become visible, nuget has to index it before it becomes available.
Once published you should be able to install it, make sure you tick the 'show pre-release packages' checkbox on the Add Packages dialog.

I'm still curious about why the linker setting didn't fix it.
Could you maybe try again and do a clean build, rebuild all a few times? (If you haven't done this already)

**Comment by markmeeus** [comment]
Hi José Paulo,

I was being too fast :-) That build is broken, I'll upload a new one soon

**Comment by agharium** [comment]
Hi Mark,

> Could you maybe try again and do a clean build, rebuild all a few times?

I'll do that as soon as I can. I'll come back with the test output in a couple of hours.

> I was being too fast :-) That build is broken, I'll upload a new one soon

I'll wait for the new build then.

Seriously, Mark, thanks for helping me on this odyssey hehe. 

The project I'm working on is my final college project. The project is a multiplatform mobile application (iOS and Android) targeting the users of a social program that the local health department holds. 

It's being pretty awesome to code it (I'm learning C# to be able to work on this project, and it is a very cool language, man), and among all the pieces that ties this project together, MarcelloDB it's surely a very important one.

I already have a couple projects coming up after college (real paid work this time, hehe) that I'm sure I'll be using Xamarin + MarcelloDB on all of them. I just loved working with C#.

Thanks again, Mark :)

**Comment by markmeeus** [comment]
Hi José Paulo,

I'm glad you like the project :-)

I have just now uploaded 1.0.8-beta2 to nuget. Go ahead and test it to see if it fixes your issues.
If it does, I'll publish a non-prerelease one.

grtz,
Mark

**Comment by agharium** [comment]
![It's Alive!](https://media.giphy.com/media/d3Kq5w84bzlBLVDO/giphy.gif)

It's working, Mark! It works with linker set to "Only SDK Assemblies" as well.

Thanks, man. You are awesome. God bless you!

**Comment by markmeeus** [comment]
HAHA, great stuff, love you enthusiasm !

I'll publish an official release later this week.

**Comment by agharium** [comment]
:)
